"""add vote table

Revision ID: 5e1354945534
Revises: cdb40d7f7f85
Create Date: 2024-09-10 22:04:05.063637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1354945534'
down_revision: Union[str, None] = 'cdb40d7f7f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'blog_id', 'user_id')
    )
    op.add_column('Blogs', sa.Column('published', sa.Boolean(), nullable=True))
    op.add_column('Blogs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('Blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Blogs', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_Blogs_id'), 'Blogs', ['id'], unique=False)
    op.create_foreign_key(None, 'Blogs', 'Users', ['user_id'], ['id'])
    op.drop_column('Blogs', 'publised')
    op.alter_column('Users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'password',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               nullable=True)
    op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_id'), table_name='Users')
    op.alter_column('Users', 'password',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('Blogs', sa.Column('publised', sa.BOOLEAN(), nullable=True))
    op.drop_constraint(None, 'Blogs', type_='foreignkey')
    op.drop_index(op.f('ix_Blogs_id'), table_name='Blogs')
    op.alter_column('Blogs', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Blogs', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Blogs', 'user_id')
    op.drop_column('Blogs', 'published')
    op.drop_table('Votes')
    # ### end Alembic commands ###
